/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardElement: typeof import('./src/components/CardElement.vue')['default']
    CardGrid: typeof import('./src/components/CardGrid.vue')['default']
    ChipElement: typeof import('./src/components/Forms/ChipElement.vue')['default']
    ChipFilter: typeof import('./src/components/Forms/ChipFilter.vue')['default']
    ChipInput: typeof import('./src/components/Forms/ChipInput.vue')['default']
    copy: (typeof import("./src/components/Forms/ChipFilter copy.vue"))["default"]
    DropdownElement: typeof import('./src/components/Forms/DropdownElement.vue')['default']
    DropdownList: typeof import('./src/components/Forms/DropdownList.vue')['default']
    FloatingActionButton: typeof import('./src/components/FloatingActionButton.vue')['default']
    ProductForm: typeof import('./src/components/ProductForm.vue')['default']
    ProductGridFilter: typeof import('./src/components/ProductGridFilter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScannerElement: typeof import('./src/components/Scanner/ScannerElement.vue')['default']
    TextInput: typeof import('./src/components/Forms/TextInput.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
  }
}
